# This is a basic workflow to help you get started with Actions

name: Deployment pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployment_pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Define env
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: npm install
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run lint
        run: npm run lint

      # Run backend test
      - name: Run backend test
        run: npm run test

      # Run e2e test
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
